version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      docker:
        patterns:
        - '*'
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      docker:
        patterns:
        - '*'
  - package-ecosystem: "composer"
    directory: "/harvester"
    schedule:
      interval: "daily"
    groups:
      docker:
        patterns:
        - '*'