version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/services/web/viewer"
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    directory: "/coins/cache-warmer/harvester"
    schedule:
      interval: "daily"
